name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'astro-web/**'
      - 'cms/**'
      - 'package.json'
      - 'package-lock.json'
      - 'Dockerfile.astro'
      - 'Dockerfile.cms'

jobs:
  build-and-push-astro:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase Repository Name
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Extract metadata (tags, labels) for Docker (Astro)
        id: meta-astro
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.REPO }}-astro
          tags: |
            type=sha,format=long
            type=raw,value=latest

      - name: Build and push Docker image (Astro)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.astro
          push: true
          tags: ${{ steps.meta-astro.outputs.tags }}
          labels: ${{ steps.meta-astro.outputs.labels }}

  build-and-push-cms:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase Repository Name
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Extract metadata (tags, labels) for Docker (CMS)
        id: meta-cms
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.REPO }}-cms
          tags: |
            type=sha,format=long
            type=raw,value=latest

      - name: Build and push Docker image (CMS)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.cms
          push: true
          tags: ${{ steps.meta-cms.outputs.tags }}
          labels: ${{ steps.meta-cms.outputs.labels }}
